apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report-service
          image: sudh1804/citylive-report-service:6
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: citylive-config
            - secretRef:
                name: citylive-secrets
          env:
            - name: PORT
              value: "5000"