apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sudh1804/citylive-frontend:6
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef: 
                name: citylive-config
          env:
            - name: PORT
              value: "3000"