apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: sudh1804/citylive-api-gateway:3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef: 
                name: citylive-config
          env:
            - name: PORT
              value: "8080"
          
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config

      volumes:
        - name: config-value
          configMap:
            name: citylive-config